name: Build

on:
  push:
    branches: ["main"]

env:
  VERSION: 0.1.${{ github.run_number }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack Kivibot.CommandLine.sln -p:Version=$VERSION --artifacts-path dist
      - name: Publish
        run: dotnet nuget push "dist/package/release/Kivibot.CommandLine.$VERSION.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key "${{ secrets.NUGET_APIKEY }}"
  tag:
    needs: ["build-and-publish"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Create tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a "$VERSION" -m "Version $VERSION"
          git push origin "$VERSION"
